easy_admin:

  site_name: Conference Guestbook

  entities:
    Conference:
      class: App\Entity\Conference
    
    Comment:
      class: App\Entity\Comment

      list:
        fields:
          - author
          - { property: 'email', type: 'email' }
          - { property: 'createdAt', type: 'datetime' }
          - { property: 'photoFilename', type: 'image', 'base_path': 'uploads/photos', label : 'Photo' }
        sort: [ 'createdAt', 'ASC' ]
        filters: [ 'conference' ]

      edit:
        fields:
          - { property: 'conference' }
          - { property: 'createdAt', type: 'datetime', type_options: { attr: { readonly: true } } }
          - 'author'
          - { property: email, type: 'email' }
          - text
